backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "data"
    label: "Data"
    files:
      - label: Projects
        name: projects
        file: "site/data/projects.yml"
        fields:
          - label: Projects
            label_singular: Project
            name: projects
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Overlay, name: overlay, widget: boolean}
              - {label: Link, name: link, widget: string}
              - {label: Description, name: description, widget: text}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        editor:
          preview: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: text, widget: text}
          - {label: Image, name: image, widget: image}
          - {label: Buttons, name: buttons, widget: list, allow_add: false, fields: [
              {label: Text, name: text, widget: string}
            ]}
          - label: Geothermal
            name: geothermal
            widget: list
            fields:
              - label: Tabs
                name: tabs
                widget: list
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
                  - {label: Text, name: text, widget: text}
          - label: About
            name: about
            widget: list
            fields:
              - label: Purpose
                name: purpose
                widget: object
                fields:
                  - {label: "Tab title", name: tab, widget: string}
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Text", name: text, widget: text}
              - label: Team
                name: team
                widget: list
                fields:
                  - {label: "Tab title", name: tab, widget: string}
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Text", name: text, widget: list}
              - label: Research
                name: research
                widget: list
                fields:
                  - {label: "Tab title", name: tab, widget: string}
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Text", name: text, widget: text}
                  - {label: "Link", name: link, widget: string}
              - label: Media
                name: media
                widget: list
                fields:
                  - {label: "Tab title", name: tab, widget: string}
                  - {label: "Heading", name: heading, widget: string}
                  - {label: "Items", name: items, widget: list, fields: [
                      {label: Link, name: link, widget: string},
                      {label: Source, name: source, widget: string},
                      {label: Image, name: image, widget: image}
                    ]}
                  - {label: "Services", name: services, widget: list, fields: [
                      {label: Icon, name: icon, widget: image},
                      {label: Link, name: link, widget: string},
                      {label: Text, name: text, widget: list}
                    ]}
